Include GUI link while reporting the newly-generated workflow ID
ihmeuw-scicomp/jobmon pull request #108
Opened 2024-03-28 17:22 UTC by k-simpson

LMK if there's a constant somewhere which has the URL format.

2024-03-28 17:26 UTC, everdyke commented
We don't store the URL format as a constant anywhere. We just use React Router in the index.tsx file to specify URL path.

2024-03-28 17:26 UTC, everdyke approved these changes

2024-04-02 18:51 UTC, mlsandar requested changes
Use the following logic.

`
from jobmon.core.configuration import JobmonConfig
config = JobmonConfig()
try:
    gui_url = config.get("http", "gui_url")
except ConfigError:
    gui_url = ""
`

and add
`
http:
    gui_url: ""
`
to jobmon.core.defaults.yaml

I will link a PR to stash where this value is actually populated for dev/stage/prod

2024-04-02 19:30 UTC, k-simpson commented
Changes implemented ✅

2024-04-12 23:13 UTC, merged